### ISSUE TITLE
Style Issues

### ISSUE THREAD

**Issue by Bigrah2** [wagerr/wagerr-explorer#5]
## Expected Behavior
looking good (shorter decimals or bigger boxes..)

## Actual Behavior
looking bad (breaks in the line)

## Steps to Reproduce the Problem

  1. Go to https://explorer.wagerr.com/#/
  1.
  1.

## Specifications

  - Version: FF 74 but with all versions in the last year, MS Edge, does not matter
  - Platform: Win 10
  - Subsystem:

![2020-03-14 13_49_50-Wagerr Block Explorer](https://user-images.githubusercontent.com/53808435/76682286-0ac37600-65fb-11ea-8296-0e3ae5cfea7d.png)

**Comment by zeroedge83** [comment]
UI revamped, and issue not longer present
